{
 "title": "Cardano Node: P2P Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(environment)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(rts_gc_current_bytes_used{environment=\"$environment\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Negotiated duplex connections (including DuplexState connections)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_duplexConns{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hot peers (active connections)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_hot{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Remote peers that have the local peer as hot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_inboundGovernor_hot{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Negotiated unidirectional connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_unidirectionalConns{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Warm peers (established but not active connection)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_warm{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Remote peers that have the local peer as warm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_inboundGovernor_warm{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_incomingConns{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cold peers (known but without established connection)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_cold{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network usefulness factor (tm): ratio of blocks served in last hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_served_block_latest_count_int{environment=\"$environment\", instance=~\"$instance\"}[1h])/rate(cardano_node_metrics_blockNum_int{environment=\"$environment\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_outgoingConns{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block propagation delay (seconds) - last 15 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.5,cardano_node_metrics_blockfetchclient_blockdelay_s{environment=\"$environment\", instance=~\"$instance\"}[15m]))",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(quantile_over_time(0.95,cardano_node_metrics_blockfetchclient_blockdelay_s{environment=\"$environment\", instance=~\"$instance\"}[15m]))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Connections relevant for pruning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_prunableConns{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within three seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfThree{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ratio of late (>5s delay) blocks in the last hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockfetchclient_lateblocks{environment=\"$environment\", instance=~\"$instance\"}[1h])/rate(cardano_node_metrics_blockNum_int{environment=\"$environment\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within five seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfFive{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}