{
 "title": "Cardano Mithril: Application metrics",
 "description": "Mithril signer metrics dashboard",
 "tags": [ "mithril" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(cardano_node_metrics_blockNum_int,environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Signer Registration Epoch",
   "type": "timeseries",
   "description": "Signer registration success epoch.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mithril_signer_signer_registration_success_last_epoch{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signer Registration Success",
   "type": "timeseries",
   "description": "Signer registration success since startup.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "mithril_signer_signer_registration_success_since_startup{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signer Registration Errors",
   "type": "timeseries",
   "description": "Signer registration errors since startup.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "mithril_signer_signer_registration_total_since_startup{environment=\"$environment\"} - mithril_signer_signer_registration_success_since_startup{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signature Registration Epoch",
   "type": "timeseries",
   "description": "Signature registration success epoch.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "mithril_signer_signature_registration_success_last_epoch{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signature Registration Success",
   "type": "timeseries",
   "description": "Signature registration success since startup.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "mithril_signer_signature_registration_success_since_startup{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signature Registration Errors",
   "type": "timeseries",
   "description": "Signature registration errors since startup.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "mithril_signer_signature_registration_total_since_startup{environment=\"$environment\"} - mithril_signer_signature_registration_success_since_startup{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Machine Cycles",
   "type": "timeseries",
   "description": "State machine cycles since startup.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "mithril_signer_runtime_cycle_total_since_startup{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Machine Cycles Success",
   "type": "timeseries",
   "description": "State machine cycle success since startup.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "mithril_signer_runtime_cycle_success_since_startup{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Machine Cycles Errors",
   "type": "timeseries",
   "description": "State machine cycle errors since startup.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "mithril_signer_runtime_cycle_total_since_startup{environment=\"$environment\"} - mithril_signer_runtime_cycle_success_since_startup{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}