{
 "title": "Cardano Node: Logs",
 "description": "start",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "log_source",
    "label": "Log Source",
    "query": "Cardano Node : cardano-node.service, Cardano Tracer : cardano-tracer.service, Cardano DB Sync : cardano-db-sync.service"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   {
    "name": "suggested_search",
    "label": "Suggested Search",
    "query": " NONE : ^, error : error, Chain extended : Chain extended\\, new tip"
   },
   { "name": "regex_search", "label": "Regex Search" },
   {
    "name": "rate_interval_mimic",
    "label": "Rate Interval",
    "query": "4m,10m,30m,1h,3h,6h,12h,24h,3d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total log lines in the time range",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({systemd_unit=\"$log_source\", environment=~\"$environment\", group=~\"$group\", instance=~\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Error log lines in the time range",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({systemd_unit=\"$log_source\", environment=~\"$environment\", group=~\"$group\", instance=~\"$instance\"} |~ \"(?i)error\"[$__range]))"
      }
     ]
    },
    {
     "title": "PeerSelection log lines in the time range",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({systemd_unit=\"$log_source\", environment=~\"$environment\", group=~\"$group\", instance=~\"$instance\"} |~ \"Net\\\\.PeerSelection\"[$__range]))"
      }
     ]
    },
    {
     "title": "Error PeerSelection log lines in the time range",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({systemd_unit=\"$log_source\", environment=~\"$environment\", group=~\"$group\", instance=~\"$instance\"} |~ \"Net\\\\.PeerSelection\" |~ \"(?i)error\" [$__range]))"
      }
     ]
    },
    {
     "title": "Log lines by Instance, per $rate_interval_mimic",
     "type": "timeseries",
     "description": "Log line quantity, per $rate_interval_mimic",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (instance) (count_over_time({systemd_unit=\"$log_source\", environment=~\"$environment\", group=~\"$group\", instance=~\"$instance\"}[$rate_interval_mimic]))\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "'Chain Extended' log lines by Instance, per $rate_interval_mimic",
     "type": "timeseries",
     "description": "Log line quantity matching 'Chain extended, new tip', per $rate_interval_mimic",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (instance) (count_over_time({systemd_unit=\"$log_source\", environment=~\"$environment\", group=~\"$group\", instance=~\"$instance\"} |~ \"Chain extended, new tip\"[$rate_interval_mimic]))\n",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Logs matching the current query",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{systemd_unit=\"$log_source\", environment=~\"$environment\", group=~\"$group\", instance=~\"$instance\"} |~ \"$${suggested_search}\" |~ \"(?i)$${regex_search}\"",
     "maxLines": 5000
    }
   ]
  }
 ]
}