{
 "title": "Cardano Node: Performance",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(cardano_node_metrics_blockNum_int,environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Delegation map growth rate (per day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(delta(cardano_node_metrics_delegMapSize_int{environment=\"$environment\"}[1h]))*24"
    },
    {
     "expr": "avg(delta(cardano_node_metrics_delegMapSize_int{environment=\"$environment\"}[24h]))"
    }
   ]
  },
  {
   "title": "UTxO growth rate (per day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(delta(cardano_node_metrics_utxoSize_int{environment=\"$environment\"}[1h]))*24"
    },
    {
     "expr": "avg(delta(cardano_node_metrics_utxoSize_int{environment=\"$environment\"}[24h]))"
    }
   ]
  },
  {
   "title": "Delegation map size",
   "type": "timeseries",
   "description": "The total number of the active delegations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cardano_node_metrics_delegMapSize_int{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UTxO size",
   "type": "timeseries",
   "description": "The total number of UTxO entries.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cardano_node_metrics_utxoSize_int{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Memory usage: 1) RSS max + avg, 2) RTS heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(cardano_node_metrics_Mem_resident_int{environment=\"$environment\",instance=~\".*-bp-.*\"})",
     "legendFormat": "max RSS"
    },
    {
     "expr": "avg(cardano_node_metrics_Mem_resident_int{environment=\"$environment\",instance=~\".*-bp-.*\"})",
     "legendFormat": "avg RSS"
    },
    {
     "expr": "max(cardano_node_metrics_RTS_gcLiveBytes_int{environment=\"$environment\",instance=~\".*-bp-.*\"})",
     "legendFormat": "max RTS gcdetails_live_bytes"
    },
    {
     "expr": "avg(cardano_node_metrics_RTS_gcLiveBytes_int{environment=\"$environment\",instance=~\".*-bp-.*\"})",
     "legendFormat": "avg RTS gcdetails_live_bytes"
    }
   ]
  },
  {
   "title": "Memory usage: RSS smoothed over 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(cardano_node_metrics_RTS_gcLiveBytes_int{environment=\"$environment\",instance=~\".*-bp-.*\"}[5m])"
    }
   ]
  },
  {
   "title": "CPU usage, % of a single core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(cardano_node_metrics_Stat_cputicks_int{environment=\"$environment\",instance=~\".*-bp-.*\"}[2m:1m]))"
    }
   ]
  },
  {
   "title": "Mempool size, tx (smoothed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(avg_over_time(cardano_node_metrics_txsInMempool_int{environment=\"$environment\"}[10m]))"
    },
    {
     "expr": "max(avg_over_time(cardano_node_metrics_txsInMempool_int{environment=\"$environment\"}[12h]))"
    }
   ]
  },
  {
   "title": "UTxO growth rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(delta(cardano_node_metrics_utxoSize_int{environment=\"$environment\"}[2m:1m]))"
    },
    {
     "expr": "avg(delta(cardano_node_metrics_utxoSize_int{environment=\"$environment\"}[1h]))/60"
    }
   ]
  },
  {
   "title": "Slot & block increments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cardano_node_metrics_slotInEpoch_int{environment=\"$environment\"})%50"
    },
    {
     "expr": "min(cardano_node_metrics_blockNum_int{environment=\"$environment\"})%50"
    }
   ]
  }
 ]
}