{
 "title": "Cardano Node: Block Performance",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(cardano_node_metrics_blockNum_int,environment)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(blockperf_block_no,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blockperf Latest Block Number",
   "type": "timeseries",
   "description": "The block number of latest sample.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_block_no{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockperf Block Delay (ms)",
   "type": "timeseries",
   "description": "Total block delay.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_block_delay{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockperf Header Delta (ms)",
   "type": "timeseries",
   "description": "The time from when a block was forged until received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_header_delta{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockperf Block Request Delta (ms)",
   "type": "timeseries",
   "description": "The time between when the header was received until the block request was sent.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_block_req_delta{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockperf Block Response Delta (ms)",
   "type": "timeseries",
   "description": "The time between when the block request was sent until the block response was received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_block_rsp_delta{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockperf Block Adopt Delta (ms)",
   "type": "timeseries",
   "description": "The time for adopting the block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_block_adopt_delta{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Iowait %",
   "type": "timeseries",
   "description": "Smoothed to a 1 minute window.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"iowait\"}[2m]))[1m:]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Ping latency (ms)",
   "type": "timeseries",
   "description": "Cardano-node ping latency measured from localhost with cardano-cli ping",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_custom_ping_latency_ms{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Restarts",
   "type": "timeseries",
   "description": "Over a 1 hr window.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase((time() - cardano_node_metrics_nodeStartTime_int{environment=\"$environment\",instance=~\"$instance\"} < bool 300)[1h:]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "round(increase((time() - cardano_node_metrics_node_start_time_int{environment=\"$environment\",instance=~\"$instance\"} < bool 300)[1h:]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockperf Valid Samples",
   "type": "timeseries",
   "description": "Valid samples collected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_valid_samples_total{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockperf Invalid Samples",
   "type": "timeseries",
   "description": "Invalid samples discarded.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockperf_invalid_samples_total{environment=\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}