{
 "title": "Systemd Logs JSON",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   {
    "name": "systemd_unit",
    "label": "Systemd Unit",
    "query": {}
   },
   { "name": "regex_search", "label": "Regex Search" },
   {
    "name": "rate_interval_mimic",
    "label": "Rate Interval",
    "query": "4m,10m,30m,1h,3h,6h,12h,24h,3d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total log lines in the time range",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({instance=~\"$instance\",systemd_unit=~\"$systemd_unit\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Error log lines in the time range",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({instance=~\"$instance\",systemd_unit=~\"$systemd_unit\"} |~ \"(?i)error\"[$__range]))"
      }
     ]
    },
    {
     "title": "Log lines by Instance, per $rate_interval_mimic",
     "type": "timeseries",
     "description": "Log line quantity, per $rate_interval_mimic",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (instance) (count_over_time({instance=~\"$instance\",systemd_unit=~\"$systemd_unit\"}[$rate_interval_mimic]))\n",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Logs",
   "type": "logs",
   "description": "All non-Cardano-Node logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{instance=~\"$instance\",systemd_unit=~\"$systemd_unit\"} |~ \"$regex_search\" | json"
    }
   ]
  }
 ]
}