# Example:
keys:
  - &sre $SOPS_AGE_PUBKEY1
  - &group1-bp-a-1 $SOPS_AGE_PUBKEY2
  - &group1-faucet-a-1 $SOPS_AGE_PUBKEY3
creation_rules:
  # -------------------------------------------------------
  # General environment secrets are admin only
  - path_regex: (secrets|workbench)/envs/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # Group no-deploy secrets are admin only
  - path_regex: (secrets|workbench)/groups/[^/]+/no-deploy/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # Group producer and other secrets
  - path_regex: secrets/groups/group1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *group1-faucet-a-1

  - path_regex: secrets/groups/group1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *group1-bp-a-1

  # -------------------------------------------------------
  # Workbench pool onboarding -- modify during creation
  # Modify and add specific block producer keys as needed
  - path_regex: workbench/groups/deploy/[^/]+/.*$
    key_groups:
    - age:
      - *sre
  #   - *EXAMPLE_MACHINE_KEY

  # -------------------------------------------------------
  # Secrets and workbench catch all
  - path_regex: (secrets|workbench)/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # State-demo functionality test
  - path_regex: state-demo/(envs|groups)/.*$
    key_groups:
    - age:
      - *sre
