{
 "title": "Cardano Db Sync: Application metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "environment", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  { "title": "Dbsync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cardano Dbsync DB Block Height",
   "type": "timeseries",
   "description": "Shows dbsync's synchronized block height.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_db_sync_db_block_height{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync Node Block Height",
   "type": "timeseries",
   "description": "Shows the block height of node as known by dbsync.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_db_sync_node_block_height{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync DB Slot Height",
   "type": "timeseries",
   "description": "Shows dbsync's synchronized slot height.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_db_sync_db_slot_height{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync To Node Block Height Difference",
   "type": "timeseries",
   "description": "Shows the difference between dbsync and node's block height.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_db_sync_node_block_height{environment=\"$environment\"} - cardano_db_sync_db_block_height{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync DB Queue Length",
   "type": "timeseries",
   "description": "Shows dbsync's queue length.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_db_sync_db_queue_length{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Registered Relays Dump Size (bytes)",
   "type": "timeseries",
   "description": "Show registered relays dump file size in bytes, if available.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "registered_relays_dump_bytes{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Registered Relays Dump Modified Time (TS)",
   "type": "timeseries",
   "description": "Show registered relays dump file modified time in unix epoch timestamp, if available.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "registered_relays_dump_mtime{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}